import { MenuItem, Deal, Review, RestaurantLocation } from "./types";

export const MENU_ITEMS: MenuItem[] = [
  // Burgers
  {
    id: "m1",
    name: "Flame-Grilled Whopper",
    category: "Burgers",
    price: 6.49,
    calories: 660,
    image: "🍔",
    isBestseller: true,
  },
  {
    id: "m2",
    name: "Double Whopper with Cheese",
    category: "Burgers",
    price: 7.99,
    calories: 900,
    image: "🍔",
    isBestseller: true,
  },
  {
    id: "m3",
    name: "Bacon King",
    category: "Burgers",
    price: 8.49,
    calories: 1150,
    image: "🥓",
  },
  {
    id: "m4",
    name: "Texas Double Whopper",
    category: "Burgers",
    price: 8.99,
    calories: 1050,
    image: "🤠",
    isNew: true,
  },
  {
    id: "m5",
    name: "Rodeo Burger",
    category: "Burgers",
    price: 2.99,
    calories: 340,
    image: "🧅",
  },
  {
    id: "m6",
    name: "Flame-Grilled Cheeseburger",
    category: "Burgers",
    price: 2.49,
    calories: 300,
    image: "🧀",
  },

  // Chicken
  {
    id: "m7",
    name: "Royal Crispy Chicken Sandwich",
    category: "Chicken",
    price: 5.99,
    calories: 600,
    image: "🍗",
  },
  {
    id: "m8",
    name: "Spicy Royal Crispy Chicken",
    category: "Chicken",
    price: 6.29,
    calories: 640,
    image: "🌶️",
    isBestseller: true,
  },
  {
    id: "m9",
    name: "BK Chicken Fries (9pc)",
    category: "Chicken",
    price: 4.49,
    calories: 290,
    image: "🍟",
    isBestseller: true,
  },
  {
    id: "m10",
    name: "Original Chicken Sandwich",
    category: "Chicken",
    price: 5.49,
    calories: 660,
    image: "🥖",
  },

  // Sides
  {
    id: "m11",
    name: "BK Classic French Fries (M)",
    category: "Sides",
    price: 3.19,
    calories: 380,
    image: "🍟",
    isBestseller: true,
  },
  {
    id: "m12",
    name: "Crispy Golden Onion Rings (M)",
    category: "Sides",
    price: 3.49,
    calories: 410,
    image: "🧅",
  },
  {
    id: "m13",
    name: "Mozzarella Sticks (4pc)",
    category: "Sides",
    price: 2.99,
    calories: 280,
    image: "🧀",
    isNew: true,
  },
  {
    id: "m14",
    name: "Cheesy Tots (8pc)",
    category: "Sides",
    price: 3.29,
    calories: 310,
    image: "🥔",
    isNew: true,
  },

  // Drinks
  {
    id: "m15",
    name: "Coca-Cola (M)",
    category: "Drinks",
    price: 1.99,
    calories: 140,
    image: "🥤",
  },
  {
    id: "m16",
    name: "Diet Coke (M)",
    category: "Drinks",
    price: 1.99,
    calories: 0,
    image: "🥤",
  },
  {
    id: "m17",
    name: "Sprite (M)",
    category: "Drinks",
    price: 1.99,
    calories: 145,
    image: "🥤",
  },
  {
    id: "m18",
    name: "Frozen Fanta Wild Cherry",
    category: "Drinks",
    price: 2.29,
    calories: 130,
    image: "🍧",
    isNew: true,
  },
];

export const DEALS: Deal[] = [
  {
    id: "d1",
    title: "$3 Whopper Wednesday",
    tagline: "Unbeatable mid-week flame-grilled goodness",
    priceText: "$3.00",
    badge: "App exclusive",
    expiresText: "Every Wednesday",
    emoji: "🍔",
  },
  {
    id: "d2",
    title: "FREE Large Fries",
    tagline: "Get a free Large Fries with any online order of $1 or more",
    priceText: "FREE",
    badge: "Daily Reset",
    expiresText: "Limited Time",
    emoji: "🍟",
  },
  {
    id: "d3",
    title: "$5 Duo Mix-n-Match",
    tagline: "Choose any two signature medium burgers or chicken entrees",
    priceText: "$5.00",
    badge: "Royal Special",
    expiresText: "Ongoing",
    emoji: "👑",
  },
  {
    id: "d4",
    title: "$12.99 Whopper Family Feast",
    tagline: "2 Whoppers, 2 Small Fries, and 2 Small soft drinks",
    priceText: "$12.99",
    badge: "Feast Deal",
    expiresText: "Mobile Checkout Only",
    emoji: "👨‍👩‍👧‍👦",
  },
];

export const REVIEWS: Review[] = [
  {
    id: "r1",
    author: "Austin Thorne",
    handle: "@WhopperFanatic99",
    rating: 5,
    content: "The flame-grilled taste is unbeatable! Whoppers are literally twice as tasty, juicy and smokey as flat fried burgers.",
    avatar: "👨‍💻",
    platform: "Google Reviews",
    date: "2 days ago",
  },
  {
    id: "r2",
    author: "Bianca G.",
    handle: "@KingBurgerGirl",
    rating: 5,
    content: "BK really lets you 'Have It Your Way'. I always double down on extra cheese and extra pickles, and the app lets me customize perfectly.",
    avatar: "👩‍🍳",
    platform: "App Store Review",
    date: "Yesterday",
  },
  {
    id: "r3",
    author: "Caleb Vance",
    handle: "@BaconRoyale",
    rating: 5,
    content: "Already redeemed my 750 Perks points for a free Flame-Grilled original Whopper! The Royal Perks program is the easiest rewards system.",
    avatar: "🧔",
    platform: "Google Reviews",
    date: "3 days ago",
  },
];

export const MOCK_RESTAURANTS: RestaurantLocation[] = [
  {
    id: "st1",
    address: "744 Flame-Grill Way",
    city: "Downtown Core",
    distance: "0.8 miles away",
    hours: "Drive-Thru Open 24/7",
    phone: "(555) 195-1954",
    features: ["24/7 Drive-Thru", "Mobile Ordering", "Playground", "Royal Perks Redemption"],
  },
  {
    id: "st2",
    address: "1208 Whopper Boulevard",
    city: "West Market District",
    distance: "1.4 miles away",
    hours: "Lobby: 6AM - Midnight • Drive-Thru: 24 Hours",
    phone: "(555) 235-WHOP",
    features: ["Mobile Ordering", "Delivery Hub", "Curbside Pickup"],
  },
  {
    id: "st3",
    address: "340 Plaza Center Drive",
    city: "Metro Station Plaza",
    distance: "2.1 miles away",
    hours: "Lobby: 7AM - 11PM • Drive-Thru: 7AM - 1AM",
    phone: "(555) 789-KING",
    features: ["Indoor Seating", "Self-Serve Kiosks", "Royal Perks Redemption"],
  },
];
